services:

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:{DB_PORT}"

  server:
    image: reffindr-node:latest
    environment:
      NODE_ENV: production
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

volumes:
  db-data:
