version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - '${PORT}:${PORT}'
    restart: always
